name: mirror-repository
description: Automate mirroring of git commits to or from a remote repository, like GitLab, Bitbucket, or another GitHub repository
branding:
  icon: git-commit
  color: green

inputs:
  REMOTE_NAME:
    description: "The remote ref name to use. 'mirror' by default. Useful to avoid conflicts with existing remotes."
    required: false
  REMOTE:
    description: "The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git"
    required: false
  GIT_USERNAME:
    description: "Username for remote repository"
    required: false
  GIT_PASSWORD:
    description: "The git https password or token for the remote repository"
    required: false
  GIT_SSH_PRIVATE_KEY:
    description: "The ssh private key for writing to the remote repository, if using ssh"
    required: false
  GIT_SSH_PUBLIC_KEY:
    description: "The ssh public key for writing to the remote repository. Normally, not required at all"
    required: false
  GIT_SSH_KNOWN_HOSTS:
    description: "The contents of a SSH known_hosts file for host key verification"
    required: false
  GIT_SSH_NO_VERIFY_HOST:
    description: "if true, skips host key verification. Mutually exclusive with GIT_SSH_KNOWN_HOSTS"
    default: "false"
    required: false
  PUSH_ALL_REFS:
    description: "Push all refs instead of just the current branch"
    default: "true"
    required: false
  GIT_PUSH_ARGS:
    description: "The arugments to use when pushing the repository"
    default: '--tags --force --prune'
    required: false
  GITHUB_REF:
    description: "The branch name to push to when not pushing all refs"
    default: ${{ github.ref }}
    required: false
  DEBUG:
    description: 'set to "true" to enable debug mode'
    default: "false"
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'
